const translations = {
    en: {language: 'Selected Language: English',
        next:'Next',
    paragraph1:'Selamun Aleykum! This application makes it easier to fulfill missed prayers and pay off your debts. Start now and repay your debts!',
    paragraph2:'The Prophet Muhammad (peace be upon him) advised his companions to make up for the prayers they missed during their prescribed times. He said, "Whoever forgets a prayer or falls asleep and misses it, should offer it when he remembers, for there is no other expiation for it." (Bukhari, Mevakit al-Salat, 37; Muslim, Masajid, 315).',
    paragraph3:'Tap the "Proceed to Calculation" button and enter the necessary information to start without wasting time. May Allah accept it.',
    scroll:'To continue, swipe to the side.' ,
    startcalculation:'Proceed to Calculation',
    birthdate:'BİRTH DATE',
    year:'YEAR',
    month:'MONTH',
    day:'DAY',
    gender:'GENDER',
    male:'MALE',
    female:'FEMALE',
    pubertyage:'PUBERTY AGE',
    monthregl:'MONTHLY REGL (DAY)',
    starterdate:'PRAYER START DATE',
    calculate:'CALCULATE',
    total :'GRAND TOTAL',
    sabah:'Morning',
    ogle:'Noon',
    ikindi:'Afternoon',
    aksam:'Evening',
    yatsi:'Night',
    okay:'Okay',
    alertWarning:'Warning',
    alertMessage1: 'Birth year must be checked.',
    alertMessage2: 'Prayer start year must be checked.',
    alertMessage3: 'Month must be entered between 0 and 12.',
    alertMessage4: 'Day must be entered between 0 and 31.',
    alertMessage5: 'Please do not use special characters.',
    alertMessage6: 'Please fill in all fields.',
},
    tr: {language: 'Seçilen Dil : Türkçe',
    next:'İleri',
    paragraph1:'Selamun Aleyküm! Bu uygulama kaçırılan namazların kaza edilmesini ve borçların ödenmesini kolaylaştırır. Şimdi başlayın ve borçlarınızı ödeyin!',
    paragraph2:'Hz. Peygamber (s.a.s.) vaktinde kılamadığı namazları kaza etmiş ve ashabına da bunu tavsiye etmiştir. Resûl-i Ekrem (s.a.s.), “Kim namazı unutursa veya uyuyup kalırsa hatırlayınca onu kılsın. Onun keffâreti ancak budur.” (Buhârî, Mevâkîtü’s-Salât, 37; Müslim, Mesâcid, 315) buyurmuştur.',
    paragraph3:'Hesaplamaya geç butonuna dokunarak gerekli bilgileri girin ve zaman kaybetmeden başlayın. Allah kabul etsin.',
    scroll:'Devam etmek için kaydırın.',
    startcalculation:'Hesaplamaya geç',
    birthdate:'DOĞUM TARİHİ',
    year:'YIL',
    month:'AY',
    day:'GÜN',
    gender:'CİNSİYET',
    male:'ERKEK',
    female:'KADIN',
    pubertyage:'ERGENLİK YAŞI',
    monthregl:'AYLIK REGL (GÜN)',
    starterdate:'NAMAZA BAŞLAMA TARİHİ',
    calculate:'HESAPLA',
    total :'GENEL TOPLAM',
    sabah:'Sabah',
    ogle:'Öğle',
    ikindi:'İkindi',
    aksam:'Akşam',
    yatsi:'Yatsı',
    okay:'Tamam',
    alertWarning:'Uyarı',
    alertMessage1:'Doğum yılı kontrol edilmelidir.',
    alertMessage2:'Namaz başlangıç yılı kontrol edilmelidir.',
    alertMessage3:'Ay 0 ile 12 arasında girilmelidir.',
    alertMessage4:'Gün 0 ile 31 arasında girilmelidir.',
    alertMessage5:'Lütfen özel karakter kullanmayınız.',
    alertMessage6:'Lütfen tüm alanları doldurunuz.',
    },
}

export {translations};